#! /bin/bash
if [[ -x $(which brew) ]]
then
    # bash completion
    if [[ -f `brew --prefix`/etc/bash_completion ]]
    then
        . `brew --prefix`/etc/bash_completion
    fi

    # completion for the brew command
    if [ -f `brew --prefix`/Library/Contributions/brew_bash_completion.sh ]
    then
        . `brew --prefix`/Library/Contributions/brew_bash_completion.sh
    fi
    
    if [ -f `brew --prefix`/etc/bash_completion.d/vagrant ]; then
      source `brew --prefix`/etc/bash_completion.d/vagrant
    fi
fi

if [[ -r "$(brew --prefix)/Library/Taps/bfontaine/homebrew-command-not-found/handler.sh" ]]; then
  . "$(brew --prefix)/Library/Taps/bfontaine/homebrew-command-not-found/handler.sh"
fi
